# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_oauthtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='renew_token',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
