# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170705_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthtoken',
            old_name='renew_token',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='oauthtoken',
            old_name='renew_token_expiration',
            new_name='refresh_token_expiration',
        ),
    ]
