# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170705_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
