# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_remove_user_azure_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuregroup',
            name='azure_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
