# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20170704_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azuregroup',
            old_name='_azure_id',
            new_name='_azure_id_name',
        ),
    ]
