# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_auto_20170704_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azuregroup',
            name='_azure_id_name',
            field=models.CharField(max_length=500),
        ),
    ]
