# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0010_auto_20170704_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azuregroup',
            name='_azure_id_name',
        ),
    ]
