# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0011_remove_azuregroup__azure_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuregroup',
            name='azure_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='azuregroup',
            name='azure_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
