# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_auto_20170704_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_fetched_groups',
            field=models.DateTimeField(blank=True, default=None, help_text='If older than 5 min, groups will be fetched from Azure next time the user makes a request?', null=True),
        ),
    ]
