# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150, verbose_name='raison')),
                ('details', models.TextField(blank=True, verbose_name='détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_va', models.CharField(blank=True, max_length=100, verbose_name='numéro de carte VA')),
                ('contact_first_name', models.CharField(max_length=300, verbose_name='prénom')),
                ('contact_last_name', models.CharField(max_length=300, verbose_name='nom de famille')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='adresse mail')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='numéro de téléphone')),
                ('contact_asso', models.CharField(blank=True, help_text="Uniquement si la réservation est faite au nom d'une association", max_length=150, verbose_name='association')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catégorie de réservation',
                'verbose_name_plural': 'catégories de réservation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='date et heure de début')),
                ('end', models.DateTimeField(verbose_name='date et heure de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True, verbose_name='valide')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='bookings.Booking', verbose_name='réservation')),
            ],
            options={
                'verbose_name': 'occurrence de réservation',
                'verbose_name_plural': 'occurrences de réservation',
            },
        ),
        migrations.CreateModel(
            name='OccurrenceResourceCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=1)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.BookingOccurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('content', models.TextField(verbose_name='contenu')),
                ('order', models.IntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'paragraphe',
                'verbose_name_plural': 'paragraphes',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'lieu',
                'verbose_name_plural': 'lieux',
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'périodicité',
                'verbose_name_plural': 'périodicités',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('booking_fee', models.PositiveIntegerField(default=0, help_text='en centimes', verbose_name='frais de location')),
                ('guarantee', models.PositiveIntegerField(default=0, help_text='en centimes', verbose_name='caution')),
                ('id_card_guarantee', models.BooleanField(default=False, verbose_name="carte d'étudiant ou carte d'identité")),
                ('public', models.BooleanField(default=True, verbose_name='public')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('day_start', models.TimeField(verbose_name='début de journée')),
                ('day_end', models.TimeField(verbose_name='fin de journée')),
                ('granularity', models.PositiveIntegerField(help_text='en minutes', verbose_name='granularité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_form', models.BooleanField(default=False, verbose_name='fiche de location')),
                ('public', models.BooleanField(default=True, verbose_name='public')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.ResourceCategory', verbose_name='catégorie parente')),
            ],
            options={
                'verbose_name': 'catégorie de ressource',
                'verbose_name_plural': 'catégories de ressource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='date et heure de début')),
                ('end', models.DateTimeField(verbose_name='date et heure de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=150)),
                ('resources', models.ManyToManyField(to='bookings.Resource', verbose_name='ressources')),
            ],
            options={
                'verbose_name': 'verrou de ressource',
                'verbose_name_plural': 'verrous de ressource',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ResourceCategory', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='resource',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Place'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='bookings.ResourceCategory', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='occurrenceresourcecount',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.Resource'),
        ),
        migrations.AddField(
            model_name='bookingoccurrence',
            name='recurrence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='bookings.Recurrence', verbose_name='périodicité'),
        ),
        migrations.AddField(
            model_name='bookingoccurrence',
            name='resources',
            field=models.ManyToManyField(through='bookings.OccurrenceResourceCount', to='bookings.Resource', verbose_name='ressources'),
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.BookingCategory', verbose_name='catégorie de réservation'),
        ),
    ]
