# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:48
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
