# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RessourceLock',
            new_name='ResourceLock',
        ),
        migrations.AlterModelOptions(
            name='bookingoccurrence',
            options={'verbose_name': 'occurrence de réservation', 'verbose_name_plural': 'occurrences de réservation'},
        ),
        migrations.AlterModelOptions(
            name='resourcelock',
            options={'verbose_name': 'verrou de ressource', 'verbose_name_plural': 'verrous de ressource'},
        ),
    ]
