# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20170321_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='order',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='order_form',
            field=models.IntegerField(default=0, help_text='Laisser à 0 pour ne pas afficher sur le formulaire de location', verbose_name='ordre sur le formulaire de location'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='order_public',
            field=models.IntegerField(default=0, help_text="Laisser à 0 pour ne pas afficher sur l'interface de réservation", verbose_name="ordre dans l'interface de réservation"),
        ),
    ]
