# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20161013_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.BookingCategory', verbose_name='catégorie de réservation'),
        ),
        migrations.AlterField(
            model_name='bookingcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking', verbose_name='réservation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.ResourceCategory', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.ResourceCategory', verbose_name='catégorie parente'),
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Resource', verbose_name='ressource'),
        ),
    ]
