# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 16:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20170523_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='end',
            field=models.DateTimeField(verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='start',
            field=models.DateTimeField(verbose_name='début'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='end',
            field=models.DateTimeField(verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='start',
            field=models.DateTimeField(verbose_name='début'),
        ),
    ]
