# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20161017_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='day_end',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='fin de journée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='day_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='début de journée'),
            preserve_default=False,
        ),
    ]
