# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20161017_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='day_end',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='day_start',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='granularity',
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='day_end',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='fin de journée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='day_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='début de journée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='granularity',
            field=models.PositiveIntegerField(default=30, verbose_name='granularité'),
            preserve_default=False,
        ),
    ]
