# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20170523_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='type',
            field=models.CharField(choices=[('A', 'Réservé association'), ('S', 'Réservé étudiant'), ('I', 'Indifférent')], default='I', max_length=1, verbose_name='type'),
        ),
    ]
