# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_resourcecategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Place', verbose_name='lieu'),
        ),
    ]
