# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20161018_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingowner',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='code barre'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='granularity',
            field=models.PositiveIntegerField(help_text='en minutes', verbose_name='granularité'),
        ),
    ]
