# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20170526_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_va',
        ),
    ]
