# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20161018_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='propriétaire'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingOwner',
        ),
    ]
