# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20161019_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='description'),
            preserve_default=False,
        ),
    ]
