# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20161019_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking', verbose_name='réservation'),
        ),
    ]
