# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20161022_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='resources',
        ),
        migrations.AddField(
            model_name='bookingoccurrence',
            name='resources',
            field=models.ManyToManyField(to='bookings.Resource', verbose_name='ressource'),
        ),
    ]
