# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20161025_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
    ]
