# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20161025_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='resources',
            field=models.ManyToManyField(to='bookings.Resource', verbose_name='ressources'),
        ),
    ]
