# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20161025_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.ResourceCategory', verbose_name='catégorie'),
        ),
    ]
