# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:50
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20161026_1056'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension()
    ]
