# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20161026_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelock',
            name='end',
            field=models.DateTimeField(verbose_name='date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='start',
            field=models.DateTimeField(verbose_name='date et heure de début'),
        ),
    ]
