# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_resourcelock_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_at'], 'verbose_name': 'réservation', 'verbose_name_plural': 'réservations'},
        ),
        migrations.AlterModelOptions(
            name='bookingcategory',
            options={'ordering': ['name'], 'verbose_name': 'catégorie de réservation', 'verbose_name_plural': 'catégories de réservation'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['category', 'name'], 'verbose_name': 'ressource', 'verbose_name_plural': 'ressources'},
        ),
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['name'], 'verbose_name': 'catégorie de ressource', 'verbose_name_plural': 'catégories de ressource'},
        ),
        migrations.AddField(
            model_name='bookingoccurrence',
            name='recursion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Recursion', verbose_name='récursion'),
        ),
    ]
