# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_auto_20161102_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursion',
            options={'verbose_name': 'récursion', 'verbose_name_plural': 'récursions'},
        ),
    ]
