# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20161102_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recursion',
            new_name='Recurrence',
        ),
        migrations.RenameField(
            model_name='bookingoccurrence',
            old_name='recursion',
            new_name='recurrence',
        ),
    ]
