# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_auto_20161102_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrence',
            options={'verbose_name': 'récurrence', 'verbose_name_plural': 'récurrences'},
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='recurrence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Recurrence', verbose_name='récurrence'),
        ),
    ]
