# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_auto_20161102_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceResourceCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingoccurrence',
            name='resources',
        ),
        migrations.AddField(
            model_name='bookingoccurrence',
            name='resources',
            field=models.ManyToManyField(through='bookings.OccurrenceResourceCount', to='bookings.Resource', verbose_name='ressources'),
        ),
        migrations.AddField(
            model_name='occurrenceresourcecount',
            name='bookingoccurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.BookingOccurrence'),
        ),
        migrations.AddField(
            model_name='occurrenceresourcecount',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Resource'),
        ),
    ]
