# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_auto_20161103_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
