# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_auto_20161203_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceresourcecount',
            name='bookingoccurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.BookingOccurrence'),
        ),
        migrations.AlterField(
            model_name='occurrenceresourcecount',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.Resource'),
        ),
    ]
