# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_auto_20161203_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrenceresourcecount',
            old_name='bookingoccurrence',
            new_name='occurrence',
        ),
    ]
