# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_auto_20161203_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrence',
            options={'verbose_name': 'périodicité', 'verbose_name_plural': 'périodicités'},
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='recurrence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Recurrence', verbose_name='périodicité'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.PositiveIntegerField(verbose_name='quantité'),
        ),
    ]
