# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_auto_20170312_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ResourceCategory', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='quantité'),
        ),
    ]
