# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_auto_20170312_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'lieu',
                'verbose_name_plural': 'lieux',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='booking_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='frais de location'),
        ),
        migrations.AddField(
            model_name='resource',
            name='guarantee',
            field=models.PositiveIntegerField(default=0, verbose_name='caution'),
        ),
        migrations.AddField(
            model_name='resource',
            name='place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Place'),
        ),
    ]
