# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_auto_20170313_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='booking_fee',
            field=models.PositiveIntegerField(default=0, help_text='en centimes', verbose_name='frais de location'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='guarantee',
            field=models.PositiveIntegerField(default=0, help_text='en centimes', verbose_name='caution'),
        ),
    ]
