# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_auto_20170313_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='id_card_guarantee',
            field=models.BooleanField(default=False, verbose_name="carte d'étudiant ou carte d'identité"),
        ),
    ]
