# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_resource_id_card_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='booking_form',
            field=models.BooleanField(default=False, verbose_name='fiche de location'),
        ),
    ]
