# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0038_resourcecategory_booking_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='bookings.Booking', verbose_name='réservation'),
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='recurrence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='bookings.Recurrence', verbose_name='périodicité'),
        ),
    ]
