# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ordre'),
        ),
    ]
