# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0042_auto_20170315_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='categories',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='bookings.ResourceCategory', verbose_name='catégorie'),
        ),
    ]
