# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0044_requiredinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_asso',
            field=models.CharField(blank=True, max_length=150, verbose_name='association'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='adresse mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_first_name',
            field=models.CharField(default='', max_length=300, verbose_name='prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_last_name',
            field=models.CharField(default='', max_length=300, verbose_name='nom de famille'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(default='', max_length=30, verbose_name='numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_va',
            field=models.CharField(blank=True, max_length=100, verbose_name='carte VA'),
        ),
    ]
