# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0045_auto_20170315_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_va',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro de carte VA'),
        ),
    ]
