# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0046_auto_20170315_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_asso',
            field=models.CharField(blank=True, help_text="Uniquement si la réservation est faite au nom d'une association", max_length=150, verbose_name='association'),
        ),
    ]
