# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0047_auto_20170315_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredinfo',
            name='categories',
        ),
        migrations.DeleteModel(
            name='RequiredInfo',
        ),
    ]
