# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0048_auto_20170315_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
